apiVersion: apps/v1
kind: Deployment
metadata:
  name: naming-server
  namespace: currency-system
  labels:
    app: naming-server

spec:
  replicas: 1

  selector:
    matchLabels:
      app: naming-server

  template:
    metadata:
      labels:
        app: naming-server
    spec:
      containers:
        - name: naming-server
          image: 295504962032.dkr.ecr.us-east-1.amazonaws.com/naming-server:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 8761

          env:
            - name: SERVER_PORT
              value: "8761"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"

          readinessProbe:
            tcpSocket:
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8761
            initialDelaySeconds: 40
            periodSeconds: 20




