spring.application.name=api-gateway
server.port=${SERVER_PORT:8765}

eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.discovery.locator.enabled=false

spring.cloud.gateway.routes[0].id=currency-exchange
spring.cloud.gateway.routes[0].uri=lb://currency-exchange
spring.cloud.gateway.routes[0].predicates[0]=Path=/currency-exchange/**

spring.cloud.gateway.routes[1].id=currency-conversion
spring.cloud.gateway.routes[1].uri=lb://currency-conversion
spring.cloud.gateway.routes[1].predicates[0]=Path=/currency-conversion/**,/currency-conversion-feign/**

management.endpoint.gateway.enabled=true
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always
management.tracing.enabled=false