apiVersion: apps/v1
kind: Deployment

metadata:
  name: currency-exchange-service
  namespace: currency-system
  labels:
    app: currency-exchange-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: currency-exchange-service

  template:
    metadata:
      labels:
        app: currency-exchange-service

    spec:
      containers:
        - name: currency-exchange-service
          image: currency-exchange-service:placeholder
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: SERVER_PORT
              value: "8000"

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE



            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: DB_NAME

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "300m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              port: 8000
              path: /actuator/health
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5