apiVersion: v1
kind: Service
metadata:
  name: currency-exchange-service
  namespace: currency-system
  labels:
    app: currency-exchange-service

spec:
  selector:
    app: currency-exchange-service

  ports:
    - port: 8000
      targetPort: 8000

  type: ClusterIP