apiVersion: apps/v1
kind: Deployment

metadata:
  name: currency-conversion-service
  namespace: currency-system
  labels:
    app: currency-conversion-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: currency-conversion-service

  template:
    metadata:
      labels:
        app: currency-conversion-service

    spec:
      containers:
        - name: currency-conversion-service
          image: currency-conversion-service:placeholder
          imagePullPolicy: Always

          ports:
            - containerPort: 8100

          env:
            - name: SERVER_PORT
              value: "8100"

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE

            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: CONFIG_SERVER_URL

            - name: CURRENCY_EXCHANGE_SERVICE_URL
              value: "http://currency-exchange-service:8000"


          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "300m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8100
            initialDelaySeconds: 25
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8100
            initialDelaySeconds: 45
            periodSeconds: 20