apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: currency-system

data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://naming-server:8761/eureka"
  ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
  TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_TRACING_ENABLED: "true"