apiVersion: v1
kind: Service
metadata:
  name: currency-exchange
  namespace: currency-system
  labels:
    app: currency-exchange

spec:
  selector:
    app: currency-exchange

  ports:
    - port: 8000
      targetPort: 8000



  type: ClusterIP
